=== mikah13/test-skt/src/schemas/schoolSite.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/OpendataDeveloperNetwork/oden-schemas/blob/master/schemas/School Sites.json",
  "title": "School Sites",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "OBJECTID": {
        "type": "integer"
      },
        "SchoolName": {
            "description": "Official institution name",
        "type": "string",
            "example": "Burnside Elementary"
      },
        "InstitutionCategory": {
            "description": "Category of the institution",
        "type": "string",
            "example": "public school"
      },
        "SchoolType": {
            "description": "School level",
        "type": "string",
            "example": "Elementary"
      },
        "Owner": {
            "description": "Property Owner",
        "type": "string",
            "example": "New Westminster School District #40y"
      },
        "Surveyed": {
            "description": "If site is surveyed",
            "type": "boolean",
            "example": "true"
      },
        "Population": {
            "description": "School student number",
            "type": "integer",
            "example": 459
      },
        "WebPageUrl": {
            "description": "Url of the school website. ",
            "type": "string",
            "example": "url"
      },
     "userInfo": {
        "type": "object",
        "properties": {
          "CREATED_USER": {
            "description": "User who created route info",
            "type": "string",
            "example": "CCARRELLI"
          },
          "CREATED_DATE": {
            "description": "Date this route info was created",
            "type": "string",
            "pattern": "[0-9]{4}-[0-9]{2}-[0-9]{2}[A-Z][0-9]{2}:[0-9]{2}:[0-9]{2}.?[0-9]{0,3}[A-Z]",
            "example": "2018-05-10T16:57:48.000Z"
          },
          "LAST_EDITED_USER": {
            "description": "User who last edited this route info",
            "type": "string",
            "example": "CCARRELLI"
          },
          "LAST_EDITED_DATE": {
            "description": "Date this route info was last edited",
            "type": "string",
            "pattern": "[0-9]{4}-[0-9]{2}-[0-9]{2}[A-Z][0-9]{2}:[0-9]{2}:[0-9]{2}.?[0-9]{0,3}[A-Z]",
            "example": "2018-05-10T16:57:48.000Z"
          }
        }
      },
    "LifeCycleStatus": {
            "description": "If property is active.",
            "type": "string",
            "example": "Active, Abandoned"
      },
    "locationData": {
        "type": "object",
        "properties": {
        "x": {
            "description": "x",
            "type": "integer",
            "example": 156
          },
        "y": {
            "description": "y",
            "type": "integer",
            "example": 156
          },
        "SHAPE_Area": {
            "description": "Area of the site. ",
            "type": "number",
            "example": 457.8
          },
        "SHAPE_Length": {
            "description": "Area of the site. ",
            "type": "number",
            "example": 457.8
          },
        "MAPID": {
            "description": "Area of the site. ",
            "type": "number",
            "example": 457.8
          }
        }
      },
    "Address": {
        "type": "object",
        "properties": {
        "StreetName": {
            "type": "string"
          },
        "StreetNumber": {
            "type": "integer"
          },
        "PostalCode": {
            "type": "string"
          },
        "City": {
            "type": "string"
          },
        "Zone": {
            "description": "Zone defined by the zone category. ",
            "type": "string",
            "example": "P-1"
          },
        "ZoneCategory": {
            "description": "How zone is defined",
            "type": "string",
            "example": "Institutional"
          },
        "Neighborhood": {
            "description": "Neighborhood",
            "type": "string",
            "example": "Victory Heights"
          }
        },
          "required":["StreetNumber","StreetName","PostalCode"]
      }
      
    },
    "required": [
      "SchoolName",
      "Address"
    ]
  }
}

=== mikah13/test-skt/src/schemas/schoolSiteDate.json
[{
      "OBJECTID":1,
        "SchoolName":"ST ANN'S ACADEMY SCHOOL",
        "InstitutionCategory":"public school",
        "SchoolType":"Elementary",
        "Owner":"New Westminster School District #40y",
        "Surveyed":true,
        "Population":459,
        "WebPageUrl":"url",
     "userInfo": {
          "CREATED_USER":"CCARRELLI",
          "CREATED_DATE":"2018-05-10T16:57:48.000Z",
          "LAST_EDITED_USER":"CCARRELLI",
          "LAST_EDITED_DATE":"2018-05-10T16:57:48.000Z"
      },
    "LifeCycleStatus":"Active",
    "locationData": {
        "x":156,
        "y":156,
        "SHAPE_Area":457.8,
        "SHAPE_Length":457.8,
        "MAPID":457.8
      },
    "Address": {
        "StreetName":"Jutland Rd",
        "StreetNumber":3130,
        "PostalCode":"V2S6X9",
        "City":"New Westminster",
        "Zone":"P-1",
        "ZoneCategory":"Institutional",
        "Neighborhood":"Victory Heights"
      }
    }
]
